import type { FormulaSetVersion } from "./types";

export const IGR_CORE_FORMULA_SET_V1: FormulaSetVersion = {
  id: "igr-core-formulas-v1-5",
  semanticVersion: "1.5.0",
  engineVersion: "igr-engine-1.5.0",
  status: "published",
  definitions: [
    {
      id: "qualified-couples",
      name: "Casais qualificados por mês",
      version: "1.0.0",
      expression: "qualifiedCouplesMonth1 × (1 + qualifiedCouplesGrowthRate)^(month - 1)",
      dependencies: ["qualifiedCouplesMonth1", "qualifiedCouplesGrowthRate"],
      description: "Projeta capacidade de captação com crescimento ou sazonalidade parametrizada.",
    },
    {
      id: "gross-sales",
      name: "Venda bruta",
      version: "1.0.0",
      expression: "qualifiedCouples × conversionRate × averageTicket",
      dependencies: ["qualified-couples", "conversionRate", "averageTicket"],
      description: "Converte volume qualificado em venda assinada antes de recebimento e perda.",
    },
    {
      id: "gross-entry-generated",
      name: "Entrada bruta gerada",
      version: "1.1.0",
      expression: "contracts × entryValuePerContract",
      dependencies: ["gross-sales", "entryValuePerContract"],
      description: "Registra a entrada contratada no mês de venda antes de perdas, taxas e prazo de liquidação.",
    },
    {
      id: "gross-receivables-generated",
      name: "Recebíveis brutos gerados",
      version: "1.0.0",
      expression: "contracts × Σ(paymentCalendar.grossAmount por contrato)",
      dependencies: ["gross-sales", "authoritative-commercial-model"],
      description: "Gera entrada, encargos explícitos e parcelas de saldo no calendário comercial da coorte.",
    },
    {
      id: "installment-collections",
      name: "Recebimento líquido de parcelas",
      version: "1.1.0",
      expression: "Σ((balance.currentCollected + balance.curedCollections) × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewMixRate", "paymentCardViewMdrRate", "paymentCardViewSettlementDays", "paymentCardInstallmentMixRate", "paymentCardInstallmentMdrRate", "paymentCardInstallmentSettlementDays", "paymentDebitMixRate", "paymentDebitMdrRate", "paymentDebitSettlementDays", "paymentRecurringChequeMixRate", "paymentRecurringChequeMdrRate", "paymentRecurringChequeSettlementDays", "paymentBoletoMixRate", "paymentBoletoMdrRate", "paymentBoletoSettlementDays"],
      description: "Separa a liquidação corrente e recuperada das parcelas de saldo, já submetida à política temporal de carteira.",
    },
    {
      id: "gross-receivables-settled",
      name: "Recebíveis brutos liquidados",
      version: "1.1.0",
      expression: "Σ((currentCollected + curedCollections) × paymentMixRate) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewSettlementDays", "paymentCardInstallmentSettlementDays", "paymentDebitSettlementDays", "paymentRecurringChequeSettlementDays", "paymentBoletoSettlementDays"],
      description: "Mostra recebimentos correntes e recuperados que chegaram ao mês de liquidação antes do MDR.",
    },
    {
      id: "canceled-receivables",
      name: "Recebíveis cancelados antes do vencimento",
      version: "1.0.0",
      expression: "Σ(grossReceivable × cancellationCurve(cohortAgeAtDue))",
      dependencies: ["gross-receivables-generated", "receivables-policy", "cancellationCurveD7", "cancellationCurveD30", "cancellationCurveD60", "cancellationCurveD90", "cancellationCurveD180", "cancellationCurveLifetime"],
      description: "Reverte recebíveis futuros conforme a sobrevivência temporal da coorte, sem misturar cancelamento com inadimplência.",
    },
    {
      id: "delinquent-balance",
      name: "Saldo inadimplente",
      version: "1.0.0",
      expression: "Σ(expectedAfterCancellation - currentCollected - curedCollections - writtenOff) no fechamento",
      dependencies: ["gross-receivables-generated", "receivables-policy", "delinquencyRate", "cureRates", "writeOffAfterDays"],
      description: "Saldo vencido e ainda aberto no fechamento do horizonte, separado de contratos cancelados.",
    },
    {
      id: "cured-collections",
      name: "Recebimentos recuperados",
      version: "1.0.0",
      expression: "Σ(openDelinquent × conditionalCureRate(bucket))",
      dependencies: ["delinquent-balance", "cureRates"],
      description: "Caixa recuperado por bucket de aging segundo curvas condicionais auditáveis.",
    },
    {
      id: "written-off-balance",
      name: "Saldo baixado para perda",
      version: "1.0.0",
      expression: "Σ(openDelinquent remanescente ao atingir writeOffAfterDays)",
      dependencies: ["delinquent-balance", "writeOffAfterDays"],
      description: "Reconhece a perda somente após a janela configurada de cobrança e cura.",
    },
    {
      id: "healthy-d90",
      name: "Healthy D90 esperado",
      version: "1.0.0",
      expression: "contracts × (1 - cancellationD90) × (1 - unresolvedDelinquencyAtD90)",
      dependencies: ["gross-sales", "receivables-policy", "cancellationCurveD90", "delinquencyRate", "cureRates"],
      description: "Quantidade esperada de contratos ativos e sem inadimplência não curada aos 90 dias.",
    },
    {
      id: "net-entry-collections",
      name: "Recebimentos líquidos",
      version: "1.3.0",
      expression: "Σ((currentCollected + curedCollections) × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewMixRate", "paymentCardViewMdrRate", "paymentCardViewSettlementDays", "paymentCardInstallmentMixRate", "paymentCardInstallmentMdrRate", "paymentCardInstallmentSettlementDays", "paymentDebitMixRate", "paymentDebitMdrRate", "paymentDebitSettlementDays", "paymentRecurringChequeMixRate", "paymentRecurringChequeMdrRate", "paymentRecurringChequeSettlementDays", "paymentBoletoMixRate", "paymentBoletoMdrRate", "paymentBoletoSettlementDays"],
      description: "Liquida entrada, encargos e parcelas por método depois de cancelamento, inadimplência, cura, MDR e prazo.",
    },
    {
      id: "pre-operational-investment",
      name: "Pré-investimento de implantação",
      version: "1.2.0",
      expression: "Σ(capexInitial × capexShareRate da frente no capexMonth da frente); na ausência de cronograma completo, capexInitial / preOperationMonths nos meses de pré-operação",
      dependencies: ["capexInitial", "preOperationMonths", "capexAcquisitionShareRate", "capexAcquisitionMonth", "capexSalesRoomShareRate", "capexSalesRoomMonth", "capexSalesKitShareRate", "capexSalesKitMonth"],
      description: "Aloca captação, sala e sales kit no mês definido; só usa distribuição uniforme quando o cronograma por rubrica ainda não foi informado por completo.",
    },
    {
      id: "commercial-team-monthly-cost",
      name: "Custo mensal da estrutura comercial",
      version: "1.0.0",
      expression: "payrollMonthly",
      dependencies: ["payrollMonthly"],
      description: "Representa a folha mensal agregada da estrutura comercial informada na Página 1.",
    },
    {
      id: "payment-terms-net-settlement",
      name: "Liquidação líquida por condição de pagamento",
      version: "1.1.0",
      expression: "Σ(receivableSchedule × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["net-entry-collections"],
      description: "Explicita que o calendário comercial combina mix, MDR e prazo antes de virar caixa.",
    },
    {
      id: "operating-cash-flow",
      name: "Fluxo de caixa operacional",
      version: "1.0.0",
      expression: "netCollections - variableCosts - partnerShare - fixedCosts - payroll - preOperationalInvestment",
      dependencies: ["net-entry-collections", "variableCostRate", "partnerShareRate", "fixedCostMonthly", "payrollMonthly", "pre-operational-investment"],
      description: "Produz caixa mensal depois de entrada líquida, custos, repasses e implantação distribuída.",
    },
    {
      id: "npv",
      name: "Valor presente líquido",
      version: "1.0.0",
      expression: "Σ operatingCashFlow_month / (1 + monthlyDiscountRate)^month",
      dependencies: ["operating-cash-flow", "discountRateAnnual"],
      description: "Desconta os fluxos mensais pela taxa mensal equivalente à taxa anual informada.",
    },
    {
      id: "irr",
      name: "Taxa interna de retorno anual",
      version: "1.0.0",
      expression: "(1 + monthlyIRR)^12 - 1",
      dependencies: ["operating-cash-flow"],
      description: "Encontra a taxa que zera o valor presente dos fluxos mensais e anualiza o resultado.",
    },
    {
      id: "payback",
      name: "Payback simples",
      version: "1.0.0",
      expression: "first month where cumulativeCashFlow >= 0, with linear interpolation",
      dependencies: ["operating-cash-flow"],
      description: "Identifica quando o fluxo de caixa acumulado deixa de ser negativo.",
    },
  ],
};
