import type { FormulaSetVersion } from "./types";

export const HARMONY_COMPAT_FORMULA_SET_V1: FormulaSetVersion = {
  id: "harmony-compat-formulas-v1",
  semanticVersion: "1.0.0",
  engineVersion: "harmony-compat-engine-v1",
  status: "published",
  definitions: [
    {
      id: "harmony-cancellation-immediate",
      name: "Cancelamento imediato Harmony",
      version: "1.0.0",
      expression: "canceledContracts_month = grossContracts_month × cancellationRate; netContracts_month = grossContracts_month - canceledContracts_month",
      dependencies: ["grossContracts", "cancellationRate"],
      description: "Aplica toda a taxa de cancelamento na própria competência da venda, sem curva temporal por coorte.",
      sourceRef: "harmony_compat_v1.cancellation.immediate",
    },
    {
      id: "harmony-delinquency-informational",
      name: "Inadimplência informativa Harmony",
      version: "1.0.0",
      expression: "monthlyExposure = scheduledCollections × 0.25; delinquentBalanceKpi = monthlyExposure no mês final; cashCollections permanece inalterado",
      dependencies: ["scheduledCollections", "delinquencyRate"],
      description: "Exibe a exposição mensal sem reduzir o caixa e usa a exposição do fechamento, não a soma de fluxos mensais, no KPI.",
      sourceRef: "harmony_compat_v1.delinquency.informational",
    },
    {
      id: "harmony-gross-entry-generated",
      name: "Entrada contratada Harmony",
      version: "1.0.0",
      expression: "grossEntryGenerated_month = netContracts_month × entryValuePerContract",
      dependencies: ["netContracts", "entryValuePerContract", "harmony-cancellation-immediate"],
      description: "Registra a entrada contratada exclusivamente sobre os contratos líquidos após cancelamento imediato.",
      sourceRef: "harmony_compat_v1.receivables.gross_entry_generated",
    },
    {
      id: "harmony-entry-settled-eight-installments",
      name: "Entrada recebida em oito parcelas Harmony",
      version: "1.0.0",
      expression: "grossEntrySettled_month = Σ(netContracts_cohort × entryValuePerContract / 8) para cohortMonth..cohortMonth+7",
      dependencies: ["netContracts", "entryValuePerContract", "harmony-cancellation-immediate"],
      description: "Distribui a entrada dos contratos líquidos de cada coorte em oito recebimentos mensais iguais.",
      sourceRef: "harmony_compat_v1.receivables.entry_settled_8x",
    },
    {
      id: "harmony-balance-settled-m5",
      name: "Saldo recebido com início em M5 Harmony",
      version: "1.0.0",
      expression: "installmentCollections_month = Σ(netContracts_cohort × (averageTicket - entryValuePerContract) / 84) para cohortMonth+4..cohortMonth+87",
      dependencies: ["netContracts", "averageTicket", "entryValuePerContract", "balanceInstallmentCount", "harmony-cancellation-immediate"],
      description: "Parcela o saldo dos contratos líquidos após cancelamento e inicia quatro meses depois da venda, equivalendo a M5 para a coorte de M1.",
      sourceRef: "harmony_compat_v1.receivables.balance_settled_m5",
    },
    {
      id: "harmony-total-receivables-settled",
      name: "Recebíveis totais liquidados Harmony",
      version: "1.0.0",
      expression: "grossReceivablesSettled = Σ(grossEntrySettled_month + installmentCollections_month)",
      dependencies: ["harmony-entry-settled-eight-installments", "harmony-balance-settled-m5"],
      description: "Soma sem dupla contagem a entrada liquidada e as parcelas de saldo liquidadas no horizonte.",
      sourceRef: "harmony_compat_v1.receivables.total_settled",
    },
    {
      id: "harmony-monthly-nominal-rate",
      name: "Taxa mensal equivalente Harmony",
      version: "1.0.0",
      expression: "monthlyRate = (1 + annualRate)^(1/12) - 1",
      dependencies: ["annualRate"],
      description: "Converte 18% a.a. para a taxa mensal equivalente usada no Golden certificado.",
      sourceRef: "COTAS_NATAL_HARMONY_GOLDEN_V1_RULES.discount_rate",
    },
    {
      id: "harmony-commission-eight-installments",
      name: "Comissão recebida em oito competências Harmony",
      version: "1.0.0",
      expression: "commissionPayments_month = Σ(netContracts_cohort × 1500 / 8) para cohortMonth..cohortMonth+7",
      dependencies: ["netContracts", "harmony-cancellation-immediate"],
      description: "Distribui a comissão provisória de R$ 1.500 por contrato líquido nas oito competências da entrada.",
      sourceRef: "harmony_compat_v1.costs.commission_1500_PENDING_policy",
    },
    {
      id: "harmony-fixed-and-payroll",
      name: "Custos fixos e folha Harmony",
      version: "1.0.0",
      expression: "fixedCosts_month = fixedCostFullMonthly × [60%,100%,100%,100%,80%,60%,50%,40%,30%,20%,10%,10%]_year; payroll = payrollMonthly",
      dependencies: ["fixedCostMonthly", "payrollMonthly"],
      description: "Aplica a curva anual completa de 144 meses sobre o custo fixo full de R$ 195.339.",
      sourceRef: "COTAS_NATAL_HARMONY_GOLDEN_V1_RULES.fixed_cost_curve",
    },
    {
      id: "harmony-line-costs",
      name: "Custos por linha Harmony",
      version: "1.0.0",
      expression: "paymentFees_month = netContracts_month × 512; variableCosts_month = netContracts_month × 425 + Σ(netContracts_cohort × price × 0.5497% / 84) de cohortMonth+4..+87; taxes_month = grossReceivablesSettled_month × 7%",
      dependencies: ["netContracts", "grossReceivablesSettled"],
      description: "Reproduz consumíveis, brinde, stress de cartão, imposto e pós-venda parcelado do Golden certificado.",
      sourceRef: "COTAS_NATAL_HARMONY_GOLDEN_V1_RULES.variable_costs",
    },
    {
      id: "harmony-pre-operational-investment",
      name: "Investimento pré-operacional Harmony",
      version: "1.0.0",
      expression: "preOperationalInvestment_month = month == 1 ? capexInitial : 0",
      dependencies: ["capexInitial"],
      description: "Exibe o pré-operacional em M1 do fluxo e o trata em t0 no VPL e na TIR.",
      sourceRef: "COTAS_NATAL_HARMONY_GOLDEN_V1_RULES.preop_timing",
    },
    {
      id: "harmony-kpis",
      name: "Indicadores financeiros Harmony",
      version: "1.0.0",
      expression: "NPV = -preOp(t0) + Σ operatingFlow_month/(1+monthlyEquivalentRate)^month; IRR = annualize(IRR([-preOp, operating M1..M144])); payback = primeiro mês com caixa acumulado >= 0; capital = max(0, -min(caixa acumulado exibido))",
      dependencies: ["operatingCashFlow", "harmony-monthly-nominal-rate"],
      description: "Deriva os indicadores com os timings certificados do Golden Harmony de 144 meses.",
      sourceRef: "COTAS_NATAL_HARMONY_GOLDEN_V1_RULES.kpis",
    },
  ],
};

export const IGR_CORE_FORMULA_SET_V1: FormulaSetVersion = {
  id: "igr-core-formulas-v1-9",
  semanticVersion: "1.9.0",
  engineVersion: "igr-engine-1.9.0",
  status: "published",
  definitions: [
    {
      id: "commercial-operations",
      name: "Capacidade e custo da operação comercial",
      version: "1.0.0",
      expression: "vendas = min(demanda dos pontos, capacidade da sala, workforce produtivo); custo incremental = workforce + treinamento",
      dependencies: ["point-economics", "room-capacity", "workforce-cohorts", "training-economics"],
      description: "Limita produção pelos gargalos físicos e humanos mensais e leva ao caixa somente custos marcados como incrementais.",
    },
    {
      id: "commission-policy",
      name: "Comissões por competência e pagamento",
      version: "1.0.0",
      expression: "base elegível × política/tier × qualidade - holdback, liquidado após cutoff + lag",
      dependencies: ["commercial-operations", "gross-sales", "gross-entry-generated", "net-entry-collections", "healthy-d90"],
      description: "Calcula competência e caixa por função/base sem contar a mesma política, base, função e mês duas vezes.",
    },
    {
      id: "point-economics",
      name: "Economia incremental dos pontos de captação",
      version: "1.0.0",
      expression: "Σ((vendas incrementais × ticket × margem de contribuição) - custo fixo mensal - vendas totais × custo por venda)",
      dependencies: ["capture-points", "authoritative-commercial-model", "receivables-policy"],
      description: "Reconcilia funil, canibalização, Healthy D90, contribuição e tratamento de caixa por ponto para decidir SCALE, OPTIMIZE ou KILL.",
    },
    {
      id: "qualified-couples",
      name: "Casais qualificados por mês",
      version: "1.1.0",
      expression: "pointEconomics.totalQualified; no modo legado, qualifiedCouplesMonth1 × (1 + qualifiedCouplesGrowthRate)^(month - 1)",
      dependencies: ["point-economics", "qualifiedCouplesMonth1", "qualifiedCouplesGrowthRate"],
      description: "Usa a capacidade reconciliada dos pontos de captação e preserva o crescimento agregado apenas no modo legado.",
    },
    {
      id: "gross-sales",
      name: "Venda bruta",
      version: "1.2.0",
      expression: "min(pointEconomics.totalSales, commercialOperations.salesCapacity) × averageTicket; no modo legado, qualifiedCouples × conversionRate × averageTicket",
      dependencies: ["qualified-couples", "point-economics", "commercial-operations", "conversionRate", "averageTicket"],
      description: "Converte produção em venda assinada depois de respeitar estoque, sala e workforce.",
    },
    {
      id: "gross-entry-generated",
      name: "Entrada bruta gerada",
      version: "1.1.0",
      expression: "contracts × entryValuePerContract",
      dependencies: ["gross-sales", "entryValuePerContract"],
      description: "Registra a entrada contratada no mês de venda antes de perdas, taxas e prazo de liquidação.",
    },
    {
      id: "gross-receivables-generated",
      name: "Recebíveis brutos gerados",
      version: "1.0.0",
      expression: "contracts × Σ(paymentCalendar.grossAmount por contrato)",
      dependencies: ["gross-sales", "authoritative-commercial-model"],
      description: "Gera entrada, encargos explícitos e parcelas de saldo no calendário comercial da coorte.",
    },
    {
      id: "installment-collections",
      name: "Recebimento líquido de parcelas",
      version: "1.1.0",
      expression: "Σ((balance.currentCollected + balance.curedCollections) × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewMixRate", "paymentCardViewMdrRate", "paymentCardViewSettlementDays", "paymentCardInstallmentMixRate", "paymentCardInstallmentMdrRate", "paymentCardInstallmentSettlementDays", "paymentDebitMixRate", "paymentDebitMdrRate", "paymentDebitSettlementDays", "paymentRecurringChequeMixRate", "paymentRecurringChequeMdrRate", "paymentRecurringChequeSettlementDays", "paymentBoletoMixRate", "paymentBoletoMdrRate", "paymentBoletoSettlementDays"],
      description: "Separa a liquidação corrente e recuperada das parcelas de saldo, já submetida à política temporal de carteira.",
    },
    {
      id: "gross-receivables-settled",
      name: "Recebíveis brutos liquidados",
      version: "1.1.0",
      expression: "Σ((currentCollected + curedCollections) × paymentMixRate) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewSettlementDays", "paymentCardInstallmentSettlementDays", "paymentDebitSettlementDays", "paymentRecurringChequeSettlementDays", "paymentBoletoSettlementDays"],
      description: "Mostra recebimentos correntes e recuperados que chegaram ao mês de liquidação antes do MDR.",
    },
    {
      id: "canceled-receivables",
      name: "Recebíveis cancelados antes do vencimento",
      version: "1.0.0",
      expression: "Σ(grossReceivable × cancellationCurve(cohortAgeAtDue))",
      dependencies: ["gross-receivables-generated", "receivables-policy", "cancellationCurveD7", "cancellationCurveD30", "cancellationCurveD60", "cancellationCurveD90", "cancellationCurveD180", "cancellationCurveLifetime"],
      description: "Reverte recebíveis futuros conforme a sobrevivência temporal da coorte, sem misturar cancelamento com inadimplência.",
    },
    {
      id: "delinquent-balance",
      name: "Saldo inadimplente",
      version: "1.0.0",
      expression: "Σ(expectedAfterCancellation - currentCollected - curedCollections - writtenOff) no fechamento",
      dependencies: ["gross-receivables-generated", "receivables-policy", "delinquencyRate", "cureRates", "writeOffAfterDays"],
      description: "Saldo vencido e ainda aberto no fechamento do horizonte, separado de contratos cancelados.",
    },
    {
      id: "cured-collections",
      name: "Recebimentos recuperados",
      version: "1.0.0",
      expression: "Σ(openDelinquent × conditionalCureRate(bucket))",
      dependencies: ["delinquent-balance", "cureRates"],
      description: "Caixa recuperado por bucket de aging segundo curvas condicionais auditáveis.",
    },
    {
      id: "written-off-balance",
      name: "Saldo baixado para perda",
      version: "1.0.0",
      expression: "Σ(openDelinquent remanescente ao atingir writeOffAfterDays)",
      dependencies: ["delinquent-balance", "writeOffAfterDays"],
      description: "Reconhece a perda somente após a janela configurada de cobrança e cura.",
    },
    {
      id: "healthy-d90",
      name: "Healthy D90 esperado",
      version: "1.0.0",
      expression: "contracts × (1 - cancellationD90) × (1 - unresolvedDelinquencyAtD90)",
      dependencies: ["gross-sales", "receivables-policy", "cancellationCurveD90", "delinquencyRate", "cureRates"],
      description: "Quantidade esperada de contratos ativos e sem inadimplência não curada aos 90 dias.",
    },
    {
      id: "net-entry-collections",
      name: "Recebimentos líquidos",
      version: "1.3.0",
      expression: "Σ((currentCollected + curedCollections) × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["gross-receivables-generated", "canceled-receivables", "cured-collections", "delinquencyRate", "paymentCardViewMixRate", "paymentCardViewMdrRate", "paymentCardViewSettlementDays", "paymentCardInstallmentMixRate", "paymentCardInstallmentMdrRate", "paymentCardInstallmentSettlementDays", "paymentDebitMixRate", "paymentDebitMdrRate", "paymentDebitSettlementDays", "paymentRecurringChequeMixRate", "paymentRecurringChequeMdrRate", "paymentRecurringChequeSettlementDays", "paymentBoletoMixRate", "paymentBoletoMdrRate", "paymentBoletoSettlementDays"],
      description: "Liquida entrada, encargos e parcelas por método depois de cancelamento, inadimplência, cura, MDR e prazo.",
    },
    {
      id: "cost-catalog-cashflow",
      name: "Ajustes do catálogo de custos",
      version: "1.0.0",
      expression: "somente linhas incremental: mensal/anual → fixedCostMonthly ou payrollMonthly; one_time → capexInitial",
      dependencies: ["costCatalogItems", "fixedCostMonthly", "payrollMonthly", "capexInitial"],
      description: "Soma custos explicitamente incrementais aos agregados do projeto; linhas legadas ou já incluídas nos totais não alteram o caixa.",
    },
    {
      id: "pre-operational-investment",
      name: "Pré-investimento de implantação",
      version: "1.3.0",
      expression: "implantação base programada + pointEconomics.incrementalCapex no mês 1",
      dependencies: ["capexInitial", "preOperationMonths", "capexAcquisitionShareRate", "capexAcquisitionMonth", "capexSalesRoomShareRate", "capexSalesRoomMonth", "capexSalesKitShareRate", "capexSalesKitMonth", "point-economics"],
      description: "Aloca implantação base e adiciona ativação de pontos apenas quando seu tratamento de caixa é incremental.",
    },
    {
      id: "commercial-team-monthly-cost",
      name: "Custo mensal da estrutura comercial",
      version: "1.0.0",
      expression: "payrollMonthly",
      dependencies: ["payrollMonthly"],
      description: "Representa a folha mensal agregada da estrutura comercial informada na Página 1.",
    },
    {
      id: "payment-terms-net-settlement",
      name: "Liquidação líquida por condição de pagamento",
      version: "1.1.0",
      expression: "Σ(receivableSchedule × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["net-entry-collections"],
      description: "Explicita que o calendário comercial combina mix, MDR e prazo antes de virar caixa.",
    },
    {
      id: "operating-cash-flow",
      name: "Fluxo de caixa operacional",
      version: "1.2.0",
      expression: "netCollections - variableCosts - partnerShare - fixedCosts - custos incrementais de pontos/operação/comissão - payroll - preOperationalInvestment",
      dependencies: ["net-entry-collections", "variableCostRate", "partnerShareRate", "fixedCostMonthly", "cost-catalog-cashflow", "point-economics", "commercial-operations", "commission-policy", "payrollMonthly", "pre-operational-investment"],
      description: "Produz caixa mensal depois de recebimentos, custos, repasses, operação, comissão, folha e implantação, respeitando os tratamentos contra dupla contagem.",
    },
    {
      id: "total-gross-contracts",
      name: "Contratos brutos acumulados",
      version: "1.0.0",
      expression: "Σ grossContracts_month",
      dependencies: ["gross-sales"],
      description: "Soma todas as vendas contratuais do horizonte, inclusive revendas de estoque devolvido por cancelamento.",
    },
    {
      id: "total-net-contracts",
      name: "Contratos líquidos acumulados",
      version: "1.0.0",
      expression: "Σ (grossContracts_month - canceledContracts_month)",
      dependencies: ["total-gross-contracts", "receivables-policy"],
      description: "Reconcilia contratos brutos com cancelamentos por coorte; no fechamento, equivale aos contratos ativos.",
    },
    {
      id: "sell-out-month",
      name: "Mês de sell-out físico",
      version: "1.0.0",
      expression: "primeiro mês em que activeContracts / maxContracts = 1",
      dependencies: ["total-net-contracts", "maxContracts"],
      description: "Identifica o primeiro mês em que contratos ativos ocupam todo o estoque físico configurado.",
    },
    {
      id: "contribution-margin",
      name: "Margem de contribuição",
      version: "1.0.0",
      expression: "Σ (netCollections - variableCosts - partnerShare - taxes), com taxes = 0 enquanto não configurados",
      dependencies: ["net-entry-collections", "gross-sales", "variableCostRate", "partnerShareRate"],
      description: "Mede a contribuição após custos variáveis e repasses; impostos permanecem explicitamente zerados até existir política configurada.",
    },
    {
      id: "operating-margin-rate",
      name: "Taxa de margem operacional",
      version: "1.0.0",
      expression: "Σ operatingResult / Σ recognizedRevenue",
      dependencies: ["contribution-margin", "fixedCostMonthly", "point-economics", "commercial-operations", "commission-policy", "payrollMonthly", "net-entry-collections"],
      description: "Divide o resultado operacional após estrutura fixa pela receita reconhecida do horizonte; fica indisponível quando a receita é zero.",
    },
    {
      id: "capital-required",
      name: "Capital requerido",
      version: "1.0.0",
      expression: "max(0, -min(cashClosing_month))",
      dependencies: ["operating-cash-flow"],
      description: "Dimensiona o aporte necessário para cobrir o menor fechamento mensal de caixa do horizonte.",
    },
    {
      id: "worst-cash-month",
      name: "Pior mês de caixa",
      version: "1.0.0",
      expression: "argmin_month(cashClosing_month)",
      dependencies: ["operating-cash-flow"],
      description: "Indica o primeiro mês em que o caixa de fechamento atinge seu menor valor no horizonte.",
    },
    {
      id: "break-even-month",
      name: "Mês de equilíbrio de caixa",
      version: "1.0.0",
      expression: "primeiro mês em que cashClosing_month >= 0",
      dependencies: ["operating-cash-flow"],
      description: "Indica o primeiro fechamento mensal não negativo; permanece indisponível quando o caixa não atinge equilíbrio.",
    },
    {
      id: "npv",
      name: "Valor presente líquido",
      version: "1.0.0",
      expression: "Σ operatingCashFlow_month / (1 + monthlyDiscountRate)^month",
      dependencies: ["operating-cash-flow", "discountRateAnnual"],
      description: "Desconta os fluxos mensais pela taxa mensal equivalente à taxa anual informada.",
    },
    {
      id: "irr",
      name: "Taxa interna de retorno anual",
      version: "1.0.0",
      expression: "(1 + monthlyIRR)^12 - 1",
      dependencies: ["operating-cash-flow"],
      description: "Encontra a taxa que zera o valor presente dos fluxos mensais e anualiza o resultado.",
    },
    {
      id: "payback",
      name: "Payback simples",
      version: "1.0.0",
      expression: "first month where cumulativeCashFlow >= 0, with linear interpolation",
      dependencies: ["operating-cash-flow"],
      description: "Identifica quando o fluxo de caixa acumulado deixa de ser negativo.",
    },
  ],
};
