import type { FormulaSetVersion } from "./types";

export const IGR_CORE_FORMULA_SET_V1: FormulaSetVersion = {
  id: "igr-core-formulas-v1",
  semanticVersion: "1.3.0",
  engineVersion: "igr-engine-1.3.0",
  status: "published",
  definitions: [
    {
      id: "qualified-couples",
      name: "Casais qualificados por mês",
      version: "1.0.0",
      expression: "qualifiedCouplesMonth1 × (1 + qualifiedCouplesGrowthRate)^(month - 1)",
      dependencies: ["qualifiedCouplesMonth1", "qualifiedCouplesGrowthRate"],
      description: "Projeta capacidade de captação com crescimento ou sazonalidade parametrizada.",
    },
    {
      id: "gross-sales",
      name: "Venda bruta",
      version: "1.0.0",
      expression: "qualifiedCouples × conversionRate × averageTicket",
      dependencies: ["qualified-couples", "conversionRate", "averageTicket"],
      description: "Converte volume qualificado em venda assinada antes de recebimento e perda.",
    },
    {
      id: "gross-entry-generated",
      name: "Entrada bruta gerada",
      version: "1.1.0",
      expression: "contracts × entryValuePerContract",
      dependencies: ["gross-sales", "entryValuePerContract"],
      description: "Registra a entrada contratada no mês de venda antes de perdas, taxas e prazo de liquidação.",
    },
    {
      id: "net-entry-collections",
      name: "Entrada líquida recebida",
      version: "1.1.0",
      expression: "Σ(grossEntryGenerated em month - floor(settlementDays / 30) × paymentMixRate × collectionRate × (1 - cancellationRate) × (1 - mdrRate))",
      dependencies: ["gross-entry-generated", "collectionRate", "cancellationRate", "paymentCardViewMixRate", "paymentCardViewMdrRate", "paymentCardViewSettlementDays", "paymentCardInstallmentMixRate", "paymentCardInstallmentMdrRate", "paymentCardInstallmentSettlementDays", "paymentDebitMixRate", "paymentDebitMdrRate", "paymentDebitSettlementDays", "paymentRecurringChequeMixRate", "paymentRecurringChequeMdrRate", "paymentRecurringChequeSettlementDays", "paymentBoletoMixRate", "paymentBoletoMdrRate", "paymentBoletoSettlementDays"],
      description: "Liquida cada parcela de entrada por método, com perda, MDR e deslocamento mensal pelo prazo informado em dias.",
    },
    {
      id: "pre-operational-investment",
      name: "Pré-investimento de implantação",
      version: "1.2.0",
      expression: "Σ(capexInitial × capexShareRate da frente no capexMonth da frente); na ausência de cronograma completo, capexInitial / preOperationMonths nos meses de pré-operação",
      dependencies: ["capexInitial", "preOperationMonths", "capexAcquisitionShareRate", "capexAcquisitionMonth", "capexSalesRoomShareRate", "capexSalesRoomMonth", "capexSalesKitShareRate", "capexSalesKitMonth"],
      description: "Aloca captação, sala e sales kit no mês definido; só usa distribuição uniforme quando o cronograma por rubrica ainda não foi informado por completo.",
    },
    {
      id: "commercial-team-monthly-cost",
      name: "Custo mensal da estrutura comercial",
      version: "1.0.0",
      expression: "payrollMonthly",
      dependencies: ["payrollMonthly"],
      description: "Representa a folha mensal agregada da estrutura comercial informada na Página 1.",
    },
    {
      id: "payment-terms-net-settlement",
      name: "Liquidação líquida por condição de pagamento",
      version: "1.0.0",
      expression: "Σ(entryGenerated × paymentMixRate × (1 - mdrRate)) no mês de liquidação",
      dependencies: ["net-entry-collections"],
      description: "Explicita que condição de pagamento combina mix, MDR e prazo antes de virar caixa.",
    },
    {
      id: "operating-cash-flow",
      name: "Fluxo de caixa operacional",
      version: "1.0.0",
      expression: "netCollections - variableCosts - partnerShare - fixedCosts - payroll - preOperationalInvestment",
      dependencies: ["net-entry-collections", "variableCostRate", "partnerShareRate", "fixedCostMonthly", "payrollMonthly", "pre-operational-investment"],
      description: "Produz caixa mensal depois de entrada líquida, custos, repasses e implantação distribuída.",
    },
    {
      id: "npv",
      name: "Valor presente líquido",
      version: "1.0.0",
      expression: "Σ operatingCashFlow_month / (1 + monthlyDiscountRate)^month",
      dependencies: ["operating-cash-flow", "discountRateAnnual"],
      description: "Desconta os fluxos mensais pela taxa mensal equivalente à taxa anual informada.",
    },
    {
      id: "irr",
      name: "Taxa interna de retorno anual",
      version: "1.0.0",
      expression: "(1 + monthlyIRR)^12 - 1",
      dependencies: ["operating-cash-flow"],
      description: "Encontra a taxa que zera o valor presente dos fluxos mensais e anualiza o resultado.",
    },
    {
      id: "payback",
      name: "Payback simples",
      version: "1.0.0",
      expression: "first month where cumulativeCashFlow >= 0, with linear interpolation",
      dependencies: ["operating-cash-flow"],
      description: "Identifica quando o fluxo de caixa acumulado deixa de ser negativo.",
    },
  ],
};
