import { describe, expect, it } from "vitest";
import { PipaRegressionCaseSchema, runPipaRegression } from "./pipaRegression";

describe("Pipa regression runner", () => {
  it("rejeita caso sem input snapshot aprovado", () => {
    expect(() => PipaRegressionCaseSchema.parse({ id: "pipa-a", formulaSetVersionId: "v1", horizonMonths: 120, inputs: {}, expected: {}, tolerance: "0.01" })).toThrow();
  });
  it("expõe erro quando um resultado esperado não respeita a tolerância", () => {
    const inputs = {
      qualifiedCouplesMonth1: { status: "provided", value: "100", sourceType: "current_decision" }, qualifiedCouplesGrowthRate: { status: "provided", value: "0", sourceType: "current_decision" }, conversionRate: { status: "provided", value: "0.1", sourceType: "current_decision" }, averageTicket: { status: "provided", value: "1000", sourceType: "current_decision" }, collectionRate: { status: "provided", value: "1", sourceType: "current_decision" }, cancellationRate: { status: "provided", value: "0", sourceType: "current_decision" }, variableCostRate: { status: "provided", value: "0", sourceType: "current_decision" }, partnerShareRate: { status: "provided", value: "0", sourceType: "current_decision" }, fixedCostMonthly: { status: "provided", value: "0", sourceType: "current_decision" }, payrollMonthly: { status: "provided", value: "0", sourceType: "current_decision" }, capexInitial: { status: "provided", value: "1", sourceType: "current_decision" }, preOperationMonths: { status: "provided", value: "0", sourceType: "current_decision" }, entryValuePerContract: { status: "provided", value: "100", sourceType: "current_decision" }, paymentCardViewMixRate: { status: "provided", value: "1", sourceType: "current_decision" }, paymentCardViewMdrRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentCardViewSettlementDays: { status: "provided", value: "0", sourceType: "current_decision" }, paymentCardInstallmentMixRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentCardInstallmentMdrRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentCardInstallmentSettlementDays: { status: "provided", value: "0", sourceType: "current_decision" }, paymentDebitMixRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentDebitMdrRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentDebitSettlementDays: { status: "provided", value: "0", sourceType: "current_decision" }, paymentRecurringChequeMixRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentRecurringChequeMdrRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentRecurringChequeSettlementDays: { status: "provided", value: "0", sourceType: "current_decision" }, paymentBoletoMixRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentBoletoMdrRate: { status: "provided", value: "0", sourceType: "current_decision" }, paymentBoletoSettlementDays: { status: "provided", value: "0", sourceType: "current_decision" }, discountRateAnnual: { status: "provided", value: "0", sourceType: "current_decision" },
    };
    expect(() => runPipaRegression({ id: "pipa-runner-contract", formulaSetVersionId: "igr-core-v1", horizonMonths: 1, inputs, expected: { npv: "0", irrAnnual: null, paybackMonths: null, totalOperatingCashFlow: "0" }, tolerance: "0" })).toThrow("VPL");
  });
});
